// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Starcatcher.Entities.Context;

#nullable disable

namespace Starcatcher.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250807182152_RelacaoDeDeletarUserCota")]
    partial class RelacaoDeDeletarUserCota
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Starcatcher.Entities.Cota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Atribuida")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("DataDeAtribuicao")
                        .HasColumnType("date");

                    b.Property<int>("GrupoConsorcioId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QteParcelas")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorDaCartaDeCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorParcela")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoConsorcioId");

                    b.HasIndex("UserId");

                    b.ToTable("Cotas");
                });

            modelBuilder.Entity("Starcatcher.Entities.GrupoConsorcio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeDoGrupo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuantidadeDeCotas")
                        .HasColumnType("int");

                    b.Property<decimal?>("TaxaAdministrativa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorTaxaAdministrativa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorTotalDoGrupoSemTaxa")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Starcatcher.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Starcatcher.Entities.Cota", b =>
                {
                    b.HasOne("Starcatcher.Entities.GrupoConsorcio", "GrupoConsorcio")
                        .WithMany("Cotas")
                        .HasForeignKey("GrupoConsorcioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Starcatcher.Entities.User", "User")
                        .WithMany("Cotas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GrupoConsorcio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Starcatcher.Entities.GrupoConsorcio", b =>
                {
                    b.Navigation("Cotas");
                });

            modelBuilder.Entity("Starcatcher.Entities.User", b =>
                {
                    b.Navigation("Cotas");
                });
#pragma warning restore 612, 618
        }
    }
}
