// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Starcatcher.Entities.Context;

#nullable disable

namespace Starcatcher.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250731163442_GrupoCotaMigrationComRelacoes3107")]
    partial class GrupoCotaMigrationComRelacoes3107
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Starcatcher.Entities.Cota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Atribuida")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("DataDeAtribuicao")
                        .HasColumnType("date");

                    b.Property<int>("GrupoConsorcioId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroCota")
                        .HasColumnType("int");

                    b.Property<int>("QteParcelas")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDaCartaDeCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorParcela")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoConsorcioId");

                    b.ToTable("Cotas");
                });

            modelBuilder.Entity("Starcatcher.Entities.GrupoConsorcio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeDeCotas")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeDeParcelas")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxaAdministrativa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotalDoGrupoComTaxa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotalDoGrupoSemTaxa")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Starcatcher.Entities.Cota", b =>
                {
                    b.HasOne("Starcatcher.Entities.GrupoConsorcio", "GrupoConsorcio")
                        .WithMany("Cotas")
                        .HasForeignKey("GrupoConsorcioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoConsorcio");
                });

            modelBuilder.Entity("Starcatcher.Entities.GrupoConsorcio", b =>
                {
                    b.Navigation("Cotas");
                });
#pragma warning restore 612, 618
        }
    }
}
